version: '3.8'

services:
  im-gateway:
    image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/im-gateway:${TAG:-latest}
    container_name: im-gateway
    restart: always
    networks:
      - im-network
    ports:
      - "8080:8080"
      - "9688:9688"
    deploy:
      resources:
        limits:
          memory: 200M
    environment:
      - SERVER_PORT=8080
      - WS_PORT=9688
      - JAVA_OPTS=-Xms138m -Xmx138m
      - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
      - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
      - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
      - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}

  im-core-server:
    image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/im-core-server:${TAG:-latest}
    container_name: im-core-server
    restart: always
    networks:
      - im-network
    ports:
      - "9601:9601"
    deploy:
      resources:
        limits:
          memory: 200M
    environment:
      - SERVER_PORT=9601
      - JAVA_OPTS=-Xms138m -Xmx138m
      - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
      - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
      - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
      - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}


  # ruoyi-auth:
  #   image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/ruoyi-auth:${TAG:-latest}
  #   container_name: ruoyi-auth
  #   restart: always
  #   networks:
  #     - im-network
  #   ports:
  #     - "9210:9210"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   environment:
  #     - SERVER_PORT=9210
  #     - JAVA_OPTS=-Xms138m -Xmx138m
  #     - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
  #     - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
  #     - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
  #     - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}



  # ruoyi-system:
  #   image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/ruoyi-system:${TAG:-latest}
  #   container_name: ruoyi-system
  #   restart: always
  #   networks:
  #     - im-network
  #   ports:
  #     - "9201:9201"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   environment:
  #     - SERVER_PORT=9201
  #     - JAVA_OPTS=-Xms138m -Xmx138m
  #     - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
  #     - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
  #     - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
  #     - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}


  # ruoyi-gen:
  #   image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/ruoyi-gen:${TAG:-latest}
  #   container_name: ruoyi-gen
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   ports:
  #     - "9202:9202"
  #   environment:
  #     - SERVER_PORT=9202
  #     - JAVA_OPTS=-Xms138m -Xmx138m
  #     - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
  #     - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
  #     - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
  #     - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}

  # ruoyi-job:
  #   image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/ruoyi-job:${TAG:-latest}
  #   container_name: ruoyi-job
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   ports:
  #     - "9203:9203"
  #   environment:
  #     - SERVER_PORT=9203
  #     - JAVA_OPTS=-Xms138m -Xmx138m
  #     - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
  #     - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
  #     - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
  #     - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}


  # ruoyi-resource:
  #   image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/ruoyi-resource:${TAG:-latest}
  #   container_name: ruoyi-resource
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   ports:
  #     - "9300:9300"
  #   environment:
  #     - SERVER_PORT=9300
  #     - JAVA_OPTS=-Xms138m -Xmx138m
  #     - SPRING_CLOUD_NACOS_SERVER_ADDR=${NACOS_SERVER:-10.1.12.11:8848}
  #     - SPRING_CLOUD_NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - SPRING_CLOUD_NACOS_PASSWORD=${NACOS_PASSWORD:-abcdimkit8989a}
  #     - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP:-DEFAULT_GROUP}
  #     - SPRING_CLOUD_NACOS_CONFIG_GROUP=${NACOS_CONFIG_GROUP:-DEFAULT_GROUP}


networks:
  im-network:
    driver: bridge
